[package]
name = "ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.2"
indexmap = "2.0.0"
lsf = { path = "../lsf" }
lz4_flex = "0.11.1"
once_cell = "1.18.0"
regex = "1.9.3"
